### ISSUE TITLE
数组随机抽取会改变原来的数组

### ISSUE THREAD

**Issue by whutyzy** [woai30231/webDevDetails#5]
在一个数组中随机抽取一部分值这个函数结尾有点小问题
```
function getArr(num,array){
		//取回原来的数组
		array = originArr;
	};
```
最后这里`array = originArr;`没有效果，因为js在传递对象类型时，表面上看是引用传递，实际上是值传递，传的是一个复制的对象，可以参考高程第四章引用类型和基本类型。
因为array没有引用外面的数组，只不过是指向的同一块数据，所以在对这块数据修改时会影响到外面的值，但是当array指向一个新的对象originArr时，两者之间就没有任何联系了。所以不要操作array，操作originArr就可以了。

**Comment by woai30231** [comment]
恩恩，我懂你的意思了，js的函数是值传递！这点确实有问题，我改过来！

**Comment by woai30231** [comment]
我知道你的意思了，js函数是值传递的，不是引用传递，这点确实有问题，我已经更新！
